version: '3.8'

volumes:
  em_ch_data:

services:
  clickhouse-server:
    image: bitnami/clickhouse:latest
    container_name: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_ADMIN_USER:
      CLICKHOUSE_ADMIN_PASSWORD:
    ports:
      - "8123:8123"    # HTTP интерфейс
      - "9000:9000"    # Нативный бинарный интерфейс
      - "9009:9009"    # Протокол Protobuf
      - "9440:9440"    # SSL/TLS (опционально, если настроено)
    volumes:
      - ./ch_data:/bitnami/clickhouse
    env_file:
      - .env
    restart: always

  emondrian:
    image: emondrian/emondrian:latest
    container_name: emondrian
    platform: linux/amd64
    restart: always
    volumes:
      - ./datasources.xml:/usr/local/tomcat/webapps/emondrian/WEB-INF/datasources.xml:ro
      - ./Foodmart.xml:/usr/local/tomcat/webapps/emondrian/WEB-INF/schema/Foodmart.xml:ro
    ports:
      - "8080:8080"
