version: '3.8'


services:
  emondrian:
    image: emondrian/emondrian:latest
    container_name: emondrian
    platform: linux/amd64
    restart: always
    volumes:
      - ./datasources.xml:/usr/local/tomcat/webapps/emondrian/WEB-INF/datasources.xml:ro
      - ./Foodmart.xml:/usr/local/tomcat/webapps/emondrian/WEB-INF/schema/Foodmart.xml:ro
    ports:
      - "8080:8080"
